<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, toRaw, watch } from 'vue'
import { useOverlayStore, type AppConfig } from '@/stores/overlay'
import { playSound, SOUND_NAMES } from '@/audio/sounds'

// store: the shared Pinia store instance. useOverlayStore is
// generated by defineStore() in stores/overlay.ts. Calling it
// returns the SAME store (socket + state) that every other
// component gets, so ControlView and the overlay page share one.
const store = useOverlayStore()

// --- backend health -----------------------------------------------------
// apiOk is a tri-state: null while the first check is in flight, then
// true/false. A dashboard light that says "down" before it has looked is
// worse than one that says nothing yet.
const apiOk = ref<boolean | null>(null)

async function checkHealth() {
  try {
    const res = await fetch('/api/health')
    apiOk.value = res.ok && (await res.json()).status === 'ok'
  } catch {
    apiOk.value = false
  }
}

// Polled rather than checked once: the panel usually stays open all stream,
// and a backend restart should light up here without a manual refresh.
let healthTimer: ReturnType<typeof setInterval> | undefined

onMounted(async () => {
  store.connect() // open (or reuse) the WebSocket
  checkHealth()
  healthTimer = setInterval(checkHealth, 10_000)
  // Fire and forget: OBS may not be running, and that must not hold up the
  // rest of the dashboard loading.
  void loadScenes()
  // Seeds the activity feed from disk so a refresh or a backend restart
  // doesn't blank it.
  void store.loadActivity()
  await store.loadConfig()
  draft.value = structuredClone(toRaw(store.config))
})

// Intervals outlive the component unless you say otherwise, and would keep
// polling (and writing to a dead ref) after navigating away.
onUnmounted(() => clearInterval(healthTimer))

// --- test alerts --------------------------------------------------------
const alertText = ref('New Follower: Innoruuk')

// The configured kinds drive the quick-fire buttons, so adding a kind to
// config.json gives you a test button for it for free.
const kindNames = computed(() => Object.keys(store.config?.alerts.kinds ?? {}))

function sendAlert(kind?: string) {
  store.send({
    type: 'alert',
    kind,
    text: alertText.value || `Test ${kind ?? 'alert'}`,
  })
}

// --- widget settings (Phase 8) ------------------------------------------
// Edited against a local draft rather than the store, so a half-typed colour
// doesn't get pushed to the overlay until you actually hit Save.
const draft = ref<AppConfig | null>(null)
const configStatus = ref('')

async function saveConfig() {
  configStatus.value = 'saving…'
  try {
    const res = await fetch('/api/config', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(draft.value),
    })
    const data = await res.json()
    configStatus.value = res.ok ? 'saved' : `error: ${JSON.stringify(data.detail)}`
  } catch (e) {
    configStatus.value = `network error: ${e}`
  }
}

// Undo without a round trip: the store's copy is whatever the backend last
// confirmed, so cloning it again throws away unsaved edits.
function revertConfig() {
  draft.value = structuredClone(toRaw(store.config))
  configStatus.value = 'reverted'
}

// --- OBS control (Phase 6) ----------------------------------------------
const obsScene = ref('')
const obsSource = ref('')
const obsStatus = ref('') // last result/error, shown under the buttons
const obsOk = ref<boolean | null>(null)

// Populated from OBS itself, so you pick from what exists rather than typing
// a name and only finding out it was wrong when OBS rejects it.
interface ObsSource {
  name: string
  visible: boolean
}
const obsScenes = ref<string[]>([])
const obsSources = ref<ObsSource[]>([])
const obsLoading = ref(false)
// OBS being closed is normal and not an error worth shouting about — the
// dropdowns just stay empty until you press Reload.
const obsReachable = ref<boolean | null>(null)

async function loadScenes() {
  obsLoading.value = true
  try {
    const res = await fetch('/api/obs/scenes')
    if (!res.ok) throw new Error((await res.json()).detail ?? res.statusText)
    const data = await res.json()
    obsScenes.value = data.scenes
    obsReachable.value = true
    // Default to whatever is live, so the panel opens on the current scene.
    if (!obsScene.value || !data.scenes.includes(obsScene.value)) {
      obsScene.value = data.current ?? data.scenes[0] ?? ''
    }
    await loadSources()
  } catch (e) {
    obsReachable.value = false
    obsScenes.value = []
    obsSources.value = []
    obsStatus.value = `${e}`
  } finally {
    obsLoading.value = false
  }
}

async function loadSources() {
  if (!obsScene.value) {
    obsSources.value = []
    return
  }
  try {
    const res = await fetch(`/api/obs/sources?scene=${encodeURIComponent(obsScene.value)}`)
    if (!res.ok) throw new Error((await res.json()).detail ?? res.statusText)
    obsSources.value = (await res.json()).sources
    // The previously selected source may not exist in the newly picked scene.
    if (!obsSources.value.some((s) => s.name === obsSource.value)) {
      obsSource.value = obsSources.value[0]?.name ?? ''
    }
  } catch (e) {
    obsSources.value = []
    obsStatus.value = `${e}`
  }
}

// Sources are per scene in OBS -- the same source carries a different
// visibility in each -- so the list reloads whenever the scene changes.
watch(obsScene, loadSources)

// Toggling visibility makes the dots in the dropdown stale, so re-read the
// scene afterwards rather than optimistically flipping our own copy: if OBS
// refused the change, the list should show what OBS actually did.
async function setSourceVisible(visible: boolean) {
  await callObs('/api/obs/source', {
    scene: obsScene.value,
    source: obsSource.value,
    visible,
  })
  await loadSources()
}

// POST a JSON body to one of our /api/obs endpoints and report how it went.
async function callObs(path: string, body: object) {
  obsStatus.value = 'sending…'
  try {
    const res = await fetch(path, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    })
    const data = await res.json()
    // FastAPI puts error text in `detail`; our success path returns `ok: true`.
    obsOk.value = res.ok
    obsStatus.value = res.ok ? `ok: ${JSON.stringify(data)}` : `error: ${data.detail}`
  } catch (e) {
    obsOk.value = false
    obsStatus.value = `network error: ${e}`
  }
}

// --- panic ----------------------------------------------------------------
// Clears every queue and hides everything on both overlays. Exists because
// when a clip is blaring at the wrong moment you do not want to be alt-tabbing
// to a terminal.
const panicStatus = ref('')

async function panic() {
  panicStatus.value = 'stopping…'
  try {
    const res = await fetch('/api/panic', { method: 'POST' })
    panicStatus.value = res.ok ? 'overlays cleared' : `error: ${res.status}`
  } catch (e) {
    panicStatus.value = `network error: ${e}`
  }
  setTimeout(() => (panicStatus.value = ''), 4000)
}

// --- activity feed ------------------------------------------------------
function clockTime(at: number) {
  return new Date(at).toLocaleTimeString([], { hour12: false })
}

// Feed rows borrow the alert's own accent colour, so a raid and a follow are
// tellable apart at a glance from across the room.
function accentFor(kind?: string) {
  return store.config?.alerts.kinds[kind || 'generic']?.accent ?? '#6272a4'
}
</script>

<template>
  <main class="dash">
    <header class="topbar">
      <h1>SANG SUITE</h1>
      <div class="pills">
        <span class="pill" :class="apiOk === null ? 'idle' : apiOk ? 'up' : 'down'">
          API {{ apiOk === null ? '…' : apiOk ? 'ok' : 'down' }}
        </span>
        <span class="pill" :class="store.connected ? 'up' : 'down'">
          WS {{ store.connected ? 'live' : 'offline' }}
        </span>
        <span class="pill" :class="obsOk === null ? 'idle' : obsOk ? 'up' : 'down'">
          OBS {{ obsOk === null ? 'untested' : obsOk ? 'ok' : 'error' }}
        </span>
      </div>
    </header>

    <div class="grid">
      <section class="card panic-card">
        <h2>Panic</h2>
        <p class="hint">Clears every queue and hides both overlays immediately.</p>
        <div class="row">
          <button class="panic" @click="panic">STOP EVERYTHING</button>
          <span v-if="panicStatus" class="status">{{ panicStatus }}</span>
        </div>
      </section>

      <section class="card">
        <h2>Test Alerts</h2>
        <label class="field">
          <span>Message</span>
          <input v-model="alertText" placeholder="New Follower: Innoruuk" />
        </label>
        <div class="row">
          <button class="primary" @click="sendAlert()">Send</button>
          <!-- No `kind` on the plain Send above, so it uses the overlay's
               'generic' styling; these fire a specific kind instead. -->
          <button v-for="name in kindNames" :key="name" @click="sendAlert(name)">
            {{ name }}
          </button>
        </div>
      </section>

      <section class="card">
        <h2>
          OBS Control
          <span class="status inline">
            {{ obsLoading ? 'loading…' : obsReachable === false ? 'OBS not reachable' : '' }}
          </span>
        </h2>
        <label class="field">
          <span>Scene</span>
          <select v-model="obsScene" :disabled="!obsScenes.length">
            <option v-if="!obsScenes.length" value="">— no scenes —</option>
            <option v-for="name in obsScenes" :key="name" :value="name">{{ name }}</option>
          </select>
        </label>
        <label class="field">
          <span>Source</span>
          <select v-model="obsSource" :disabled="!obsSources.length">
            <option v-if="!obsSources.length" value="">— no sources —</option>
            <!-- The dot marks what OBS currently has visible, so Show/Hide
                 isn't a guess. It's a snapshot from the last load, not live. -->
            <option v-for="s in obsSources" :key="s.name" :value="s.name">
              {{ s.visible ? '●' : '○' }} {{ s.name }}
            </option>
          </select>
        </label>
        <div class="row">
          <button
            class="primary"
            :disabled="!obsScene"
            @click="callObs('/api/obs/scene', { scene: obsScene })"
          >
            Switch Scene
          </button>
          <button :disabled="!obsSource" @click="setSourceVisible(true)">Show</button>
          <button :disabled="!obsSource" @click="setSourceVisible(false)">Hide</button>
          <!-- Scenes and sources change in OBS while this page is open, and
               nothing pushes that to us, so there has to be a manual reload. -->
          <button class="icon" title="Reload from OBS" @click="loadScenes">⟳</button>
        </div>
        <p class="status">{{ obsStatus || '—' }}</p>
      </section>

      <section class="card wide" v-if="draft">
        <h2>
          Alert Settings
          <span class="status inline">{{ configStatus }}</span>
        </h2>
        <div class="row">
          <label class="field">
            <span>Duration (ms)</span>
            <input v-model.number="draft.alerts.duration_ms" type="number" min="500" max="60000" />
          </label>
          <label class="field grow">
            <span>Volume — {{ Math.round(draft.alerts.volume * 100) }}%</span>
            <input v-model.number="draft.alerts.volume" type="range" min="0" max="1" step="0.05" />
          </label>
        </div>

        <!-- Every control here previews against the draft, so you can dial a kind
             in by ear before saving anything to the overlay. -->
        <div class="kinds">
          <div class="kind-head">
            <span>Kind</span><span>Label</span><span>Accent</span><span>Sound</span><span></span>
          </div>
          <div v-for="(kind, name) in draft.alerts.kinds" :key="name" class="kind-row">
            <span class="kind-name" :style="{ borderColor: kind.accent }">{{ name }}</span>
            <input v-model="kind.label" />
            <input v-model="kind.accent" type="color" />
            <select v-model="kind.sound">
              <option v-for="sound in SOUND_NAMES" :key="sound" :value="sound">{{ sound }}</option>
            </select>
            <button class="icon" title="Preview" @click="playSound(kind.sound, draft.alerts.volume)">
              ▶
            </button>
          </div>
        </div>

        <div class="row">
          <button class="primary" @click="saveConfig">Save Settings</button>
          <button @click="revertConfig">Revert</button>
        </div>
      </section>

      <section class="card wide">
        <h2>
          Activity
          <span class="status inline">{{ store.recentEvents.length }} event(s)</span>
        </h2>
        <p v-if="!store.recentEvents.length" class="status">
          Nothing yet — fire a test alert or wait for Twitch.
        </p>
        <ul class="feed">
          <li v-for="event in store.recentEvents" :key="event.id">
            <span class="time">{{ clockTime(event.at) }}</span>
            <span class="tag" :style="{ color: accentFor(event.kind), borderColor: accentFor(event.kind) }">
              {{ event.kind || event.type }}
            </span>
            <span class="text">{{ event.text }}</span>
            <span class="amount">{{ event.amount ?? '' }}</span>
          </li>
        </ul>
      </section>
    </div>
  </main>
</template>

<style scoped>
@font-face {
  font-family: 'Departure Mono';
  src: local('Departure Mono'), url('/fonts/DepartureMono-Regular.otf') format('opentype');
  font-display: block;
}

/* Dracula-ish palette, kept as variables so the cards, pills and feed all
   pull from one place instead of repeating hex codes. */
.dash {
  --bg: #21222c;
  --panel: #282a36;
  --line: #44475a;
  --text: #f8f8f2;
  --dim: #6272a4;
  --accent: #bd93f9;
  --up: #50fa7b;
  --down: #ff5555;

  font-family: 'Departure Mono', ui-monospace, monospace;
  color: var(--text);
  background: var(--bg);
  min-height: 100vh;
  padding: 20px;
}

.topbar {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  align-items: center;
  justify-content: space-between;
  padding-bottom: 14px;
  border-bottom: 1px solid var(--line);
}

.topbar h1 {
  font-size: 20px;
  letter-spacing: 0.4em;
  color: var(--accent);
}

.pills {
  display: flex;
  gap: 8px;
}

.pill {
  font-size: 12px;
  padding: 3px 10px;
  border: 1px solid var(--line);
  border-radius: 999px;
  color: var(--dim);
}

.pill.up {
  color: var(--up);
  border-color: var(--up);
}
.pill.down {
  color: var(--down);
  border-color: var(--down);
}

/* auto-fit + minmax: as many columns as fit at 340px, then they stretch.
   No breakpoints needed — the panel reflows to one column on a narrow
   window or a phone by itself. */
.grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(340px, 1fr));
  gap: 16px;
  align-items: start;
  margin-top: 16px;
}

.card {
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: 6px;
  padding: 14px 16px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

/* The settings and feed cards want the full width when there's room for
   two columns; 1 / -1 means "first grid line to last". */
.card.wide {
  grid-column: 1 / -1;
}

.card h2 {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: 10px;
  font-size: 13px;
  letter-spacing: 0.25em;
  color: var(--dim);
  text-transform: uppercase;
}

.field {
  display: flex;
  flex-direction: column;
  gap: 4px;
  font-size: 12px;
  color: var(--dim);
}

.field.grow {
  flex: 1;
  min-width: 180px;
}

.row {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  align-items: flex-end;
}

input,
select {
  font: inherit;
  font-size: 14px;
  color: var(--text);
  background: var(--bg);
  border: 1px solid var(--line);
  border-radius: 4px;
  padding: 6px 8px;
}

input[type='color'] {
  padding: 2px;
  width: 44px;
  height: 32px;
}

input[type='range'] {
  padding: 0;
  accent-color: var(--accent);
}

input:focus,
select:focus {
  outline: none;
  border-color: var(--accent);
}

button {
  font: inherit;
  font-size: 13px;
  color: var(--text);
  background: var(--line);
  border: 1px solid transparent;
  border-radius: 4px;
  padding: 7px 14px;
  cursor: pointer;
}

button:hover {
  border-color: var(--accent);
}

button.primary {
  background: var(--accent);
  color: #21222c;
}

button.icon {
  padding: 7px 10px;
}

/* Deliberately the loudest thing on the page — it gets used in a hurry. */
button.panic {
  background: #c32222;
  color: #fff;
  font-weight: 700;
  letter-spacing: 0.08em;
  padding: 12px 18px;
}

button.panic:hover {
  background: #e02b2b;
}

.panic-card {
  border-color: #c32222;
}

.hint {
  margin: 0 0 10px;
  font-size: 12px;
  color: var(--dim);
}

/* OBS closed, or a scene with no sources — don't offer a button that can
   only fail. */
button:disabled,
select:disabled {
  opacity: 0.45;
  cursor: not-allowed;
}

button:disabled:hover {
  background: var(--bg);
}

.status {
  font-size: 12px;
  color: var(--dim);
}

.status.inline {
  letter-spacing: 0;
  text-transform: none;
}

/* One grid for the header and every kind row, so the columns line up
   without a <table>. */
.kinds {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.kind-head,
.kind-row {
  display: grid;
  grid-template-columns: 90px minmax(120px, 1fr) 44px minmax(110px, 160px) auto;
  gap: 8px;
  align-items: center;
}

.kind-head {
  font-size: 11px;
  letter-spacing: 0.1em;
  color: var(--dim);
  text-transform: uppercase;
}

.kind-name {
  font-size: 13px;
  padding: 4px 8px;
  border-left: 3px solid var(--line);
}

.feed {
  list-style: none;
  padding: 0;
  margin: 0;
  max-height: 320px;
  overflow-y: auto;
}

.feed li {
  display: grid;
  grid-template-columns: 80px 90px 1fr auto;
  gap: 10px;
  align-items: baseline;
  padding: 6px 0;
  border-bottom: 1px solid var(--line);
  font-size: 13px;
}

.feed .time {
  color: var(--dim);
  font-size: 12px;
}

.feed .tag {
  font-size: 11px;
  text-align: center;
  padding: 1px 6px;
  border: 1px solid;
  border-radius: 3px;
  text-transform: uppercase;
}

.feed .text {
  overflow-wrap: anywhere;
}

.feed .amount {
  color: var(--dim);
}
</style>
