<script setup lang="ts">
import { ref, onMounted, toRaw } from 'vue'
import { useOverlayStore, type AppConfig } from '@/stores/overlay'
import { playSound, SOUND_NAMES } from '@/audio/sounds'

// status: a reactive container, starting as '...'.
// "Reactive" = when its value changes, Vue re-renders anything
// in the template that uses it. Read/write it via .value in
// <script>, but just `status` in the <template> (Vue unwraps it).
const status = ref('...')
// store: the shared Pinia store instance. useOverlayStore is
// generated by defineStore() in stores/overlay.ts. Calling it
// returns the SAME store (socket + state) that every other
// component gets, so ControlView and the overlay page share one.
const store = useOverlayStore()

// onMounted: run once, right after this component first renders.
onMounted(async () => {
  store.connect() // open (or reuse) the WebSocket
  // one-time health check: GET /api/health, then stash its
  // "status" field into our ref so the template shows it
  const res = await fetch('/api/health')
  status.value = (await res.json()).status
})

// --- widget settings (Phase 8) ---
// Edited against a local draft rather than the store, so a half-typed colour
// doesn't get pushed to the overlay until you actually hit Save.
const draft = ref<AppConfig | null>(null)
const configStatus = ref('')

onMounted(async () => {
  await store.loadConfig()
  draft.value = structuredClone(toRaw(store.config))
})

async function saveConfig() {
  configStatus.value = 'saving…'
  try {
    const res = await fetch('/api/config', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(draft.value),
    })
    const data = await res.json()
    configStatus.value = res.ok ? 'saved' : `error: ${JSON.stringify(data.detail)}`
  } catch (e) {
    configStatus.value = `network error: ${e}`
  }
}

// --- OBS control (Phase 6) ---
// Editable so you can point them at whatever your OBS actually has.
const obsScene = ref('Scene')
const obsSource = ref('MySource')
const obsStatus = ref('') // last result/error, shown under the buttons

// POST a JSON body to one of our /api/obs endpoints and report how it went.
async function callObs(path: string, body: object) {
  obsStatus.value = 'sending…'
  try {
    const res = await fetch(path, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    })
    const data = await res.json()
    // FastAPI puts error text in `detail`; our success path returns `ok: true`.
    obsStatus.value = res.ok ? `ok: ${JSON.stringify(data)}` : `error: ${data.detail}`
  } catch (e) {
    obsStatus.value = `network error: ${e}`
  }
}
</script>

<template>
  <main>
    <h1>Control Panel</h1>
    <p>Backend: {{ status }}</p>
    <p>WS: {{ store.connected }}</p>
    <button @click="store.send({ type: 'alert', text: 'New Follower: Innoruuk' })">Send Alert</button>

    <h2>Alert Settings</h2>
    <template v-if="draft">
      <p>
        Duration (ms):
        <input v-model.number="draft.alerts.duration_ms" type="number" min="500" max="60000" />
      </p>
      <p>
        Sound volume:
        <input v-model.number="draft.alerts.volume" type="range" min="0" max="1" step="0.05" />
        {{ Math.round(draft.alerts.volume * 100) }}%
      </p>
      <!-- Every control here previews against the draft, so you can dial a kind
           in by ear before saving anything to the overlay. -->
      <p v-for="(kind, name) in draft.alerts.kinds" :key="name">
        <strong>{{ name }}</strong>
        <input v-model="kind.label" />
        <input v-model="kind.accent" type="color" />
        <select v-model="kind.sound">
          <option v-for="sound in SOUND_NAMES" :key="sound" :value="sound">{{ sound }}</option>
        </select>
        <button @click="playSound(kind.sound, draft.alerts.volume)">▶</button>
      </p>
      <button @click="saveConfig">Save Settings</button>
      <p>Config: {{ configStatus }}</p>
    </template>

    <h2>OBS Control</h2>
    <p>
      Scene: <input v-model="obsScene" />
      Source: <input v-model="obsSource" />
    </p>
    <button @click="callObs('/api/obs/scene', { scene: obsScene })">Switch to Scene</button>
    <button @click="callObs('/api/obs/source', { scene: obsScene, source: obsSource, visible: true })">Show Source</button>
    <button @click="callObs('/api/obs/source', { scene: obsScene, source: obsSource, visible: false })">Hide Source</button>
    <p>OBS: {{ obsStatus }}</p>
  </main>
</template>

<style scoped>

main {
  color: white;
  background-color: purple;
  min-height: 100vh;
  padding: 20px
}

</style>
